import { PICOSCriteria, Paper, PRISMACounts } from "./types";

export const initialPICOS: PICOSCriteria = {
  title: "Effectiveness of Human Insulin vs. Analogues in Diabetic Patients aged < 18",
  population: "Toddlers, children, adolescents (<18 years old) with Diabetes Mellitus Type 1 or Type 2",
  intervention: "Human insulin (NPH, Neutral, or long-acting formulation)",
  comparator: "Insulin analogues (Lispro, Aspart, Glargine, Detemir)",
  outcomes: "Glycated hemoglobin (HbA1c), frequency of hypoglycemia, adverse glycemic events, quality of life",
  studyDesigns: "Randomized Controlled Trials (RCTs) or controlled clinical trials",
  languageRestrictions: "English only (due to clinical sifting resources)",
  publicationStatus: "Peer-reviewed published journal articles"
};

export const samplePapers: Paper[] = [
  {
    id: "insulin-study-1",
    citation: "Amling 2018",
    title: "Efficacy and safety of human neutral protamine Hagedorn (NPH) insulin versus glargine analog in pediatric type 1 diabetes",
    authors: "Amling M., Petersen K., Müller G.",
    year: "2018",
    journal: "Journal of Pediatric Endocrinology",
    abstract: "A randomized controlled trial of 120 patients aged 4 to 17 years with type 1 diabetes. Patients were split into two groups: 60 patients received traditional human NPH insulin twice daily, and 60 patients received glargine analogue once daily. Efficacy was monitored over a 12-month duration. Primary outcomes showed a mean HbA1c reduction of 0.6% in both groups, but glargine patients reported 25% fewer nocturnal mild hypoglycemia events (p = 0.041). Blinding was maintained for outcome assessors, with computer-regulated allocation.",
    screeningStatus: "unscreened",
    screeningReason: ""
  },
  {
    id: "insulin-study-2",
    citation: "Rodriguez 2021",
    title: "Glycemic control comparison of short-acting human insulin with rapid analogue analogs in active children",
    authors: "Rodriguez S., Chang L., Davis T.",
    year: "2021",
    journal: "Archives of Child Health",
    abstract: "A double-blind, multicenter randomized study investigating human regular insulin against rapid insulin aspart analogue. The study included 85 pediatric individuals (aged 6 to 14) with a baseline HbA1c of 8.2%. Group A received pre-meal human regular insulin (30 minutes prior), while Group B received post-meal rapid aspart analogue. Continuous glucose monitoring over 24 weeks indicated rapid analog had tighter postprandial control. Allocation sequence was generated by block randomization, and investigator blinding was complete.",
    screeningStatus: "unscreened",
    screeningReason: ""
  },
  {
    id: "insulin-study-3",
    citation: "Tanaka 2019",
    title: "Qualitative lived experiences of children on insulin analogue treatment pumps versus human insulin syringe injections",
    authors: "Tanaka Y., Sato H.",
    year: "2019",
    journal: "Endocrine Practice Quarterly",
    abstract: "An interview-based qualitative analysis of 15 adolescents with Type 1 Diabetes Mellitus. Semi-structured interviews explored patient and parent attitudes, daily compliance hurdles, school-setting issues, and visual comfort. Results indicated that while pump analogue users felt greater freedom, traditional human insulin injections created stronger structured scheduling habits. The study design does not contain any comparative quantitative trial or randomized outcomes.",
    screeningStatus: "unscreened",
    screeningReason: ""
  },
  {
    id: "insulin-study-4",
    citation: "Golder 2020",
    title: "Long-term retrospective cohort survey of insulin analogue glargine safety in diabetic adults",
    authors: "Golder S., Miller J.",
    year: "2020",
    journal: "Adult Diabetes & Metabolism Journal",
    abstract: "A retrospective cohort study of 2,400 adult diabetes patients over a 5-year study timeframe. The cohort analyzed long-term vascular adverse effects and cancer risks among those on analog glargine compared to human NPH. Adjusting for age, sex, and cigarette smoking risk factors, no significant difference in hazard ratios was found. The study strictly included individuals aged 25 to 65 years.",
    screeningStatus: "unscreened",
    screeningReason: ""
  }
];

export const initialPRISMACounts: PRISMACounts = {
  recordsIdentified: 1520,
  recordsRemovedDuplicates: 490,
  recordsScreened: 1030,
  recordsExcluded: 910,
  reportsSoughtForRetrieval: 120,
  reportsNotRetrieved: 5,
  reportsAssessedForEligibility: 115,
  reportsExcludedNearMisses: 69,
  studiesIncluded: 46
};

export const sampleReferences = [
  "Page MJ, McKenzie JE, Bossuyt PM, Boutron I, Hoffmann TC, Mulrow CD, et al. The PRISMA 2020 statement: an updated guideline for reporting systematic reviews. BMJ. 2021;372:n71.",
  "STARLITE standard: Booth A. 'Brimful of STARLITE': Toward standards for reporting literature searches. J Med Libr Assoc. 2006;94(4):421-429.",
  "Higgins JPT, Thomas J, Chandler J, Cumpston M, Li T, Page MJ, Welch V, editors. Cochrane Handbook for Systematic Reviews of Interventions version 6.4 (updated August 2023). Cochrane; 2023.",
  "PRESS checklist: Canadian Agency for Drugs and Technologies in Health. PRESS: Peer review of electronic search strategies. Ottawa: CADTH; 2008.",
  "QUADAS-2 tool: Whiting PF, Rutjes AW, Westwood ME, Mallett S, et al. QUADAS-2: a revised tool for the quality assessment of diagnostic accuracy studies. Ann Intern Med. 2011;155(8):529-536.",
  "AMSTAR 2 checklist: Shea BJ, Reeves BC, Wells G, et al. AMSTAR 2: a critical appraisal tool for systematic reviews that include randomised or non-randomised studies of healthcare interventions, or both. BMJ. 2017;358:j4008.",
  "Jadad Scale: Jadad AR, Moore RA, Carroll D, et al. Assessing the quality of reports of randomized clinical trials: Is blinding necessary? Controlled Clinical Trials. 1996;17(1):1-12."
];
